### PR TITLE
Replace Data.FileCache with a plain cache with no watch

### PR DESCRIPTION
**Pull request by PierreR**
Watching for file changes it useless in the current client only setting.

If a server settings is set up, it would be nice to change the filecache package
to work with OS X. That would anyway require changing the APIs because the
underline fsnotify package is using a 'withXXX' pattern.

### CODE REVIEW

**Comment by PierreR** [comment]
I don't know if this is a good idea but the point of this PR is to fix #197 (as I have now two interested users on OSX).

I am unsure about https://github.com/bartavelle/filecache/blob/master/Data/FileCache.hs#L75. Is 'id' a way to catch everything else ? Is it useful without the watch ?

**Comment by bartavelle** [comment]
`id` is indeed here to catch all the other exceptions. It sucks that function types do not explain what type of exceptions they can throw, so I do not really know if there are other kind of exceptions (division by 0?).

However, I would rather keep the filecache functionality. Isn't it possible to alter filecache so that it uses polling on non Linux OSes?

**Comment by PierreR** [comment]
I first try to add OS X support in FileCache but as I am saying in the commit message I believe this would require changing the FileCache API. It seems odd that the current FileCache implementation is doing an `initINotify` without any clean up (providing instead a `killFileCache` function that is not used in `language-puppet`). At that point, I thought that it might be a good idea to just use a plain cache because the watching feature is not used today.

**Comment by bartavelle** [comment]
Why would another type of cache require an API change?

**Comment by PierreR** [comment]
To be more precise, even if this doesn't look like a big deal. initDaemon would become `withDaemon ....` because fsnotify works with a `withManager ...`

**Comment by bartavelle** [comment]
Those are details that are hidden by the cache implementation. The cache could run another thread that handles the events (just like the inotify package does as I understand it).

**Comment by bartavelle** [comment]
`killFileCache` calls `killINotify`.

**Comment by PierreR** [comment]
Yep but where is it called ?

**Comment by bartavelle** [comment]
It is not called in the puppet daemon, as it is not (yet) required.

**Comment by bartavelle** [comment]
This is for other uses of this library, where you might want to stop watching at some point.

**Comment by PierreR** [comment]
My understanding of `fsnotify` is that you need to kill the manager as soon as you decide to initialize one. That's why `withManager` is provided. It actually seems odd to me that you would initialize with `initINotify` (as the cache is doing currently) and then don't kill anything because it is not (yet) required ?

**Comment by PierreR** [comment]
But of course we could do the same with `fsnotify`. Initialize a manager and never kill them. It just seems a bit dangerous to me.

**Comment by bartavelle** [comment]
You would need to kill the watch as soon as you want the  "demon thread"  to stop. In a server situation, this means never. In the `puppetresources` program, this happens when the program stops.

in `fsnotify`, `withManager` is just `bracket (startManagerConf conf) stopManager`.

**Comment by bartavelle** [comment]
Apparently the fsnotify package can't just watch a file. This is annoying, but manageable.

**Comment by PierreR** [comment]
When using the puppetresouces programs there is no need to stop the manager or kill inotify as this is kind of happening by the fact the program dies ?

**Comment by bartavelle** [comment]
Exactly! Just like you do not need to close open file handles, or free remaining memory, the kernel does that for you.

**Comment by PierreR** [comment]
Ok that's something I was unsure about :-)

It seems possible to watch only one file by just appending the file with '/'. This is what https://hackage.haskell.org/package/spy is doing if I read the code correctly.

**Comment by bartavelle** [comment]
I'll try to adapt the filecache

**Comment by PierreR** [comment]
Thanks ;-)

**Comment by bartavelle** [comment]
I do not believe it can watch a single file, this throws exceptions :(

**Comment by PierreR** [comment]
I have skimmed this issue https://github.com/haskell-fswatch/hfsnotify/issues/32 and the related https://github.com/haskell-fswatch/hfsnotify/issues/41

**Comment by bartavelle** [comment]
I updated the filecache git, but have not really tested it. I updated the test suite though!

**Comment by bartavelle** [comment]
Well, if you understand what is going on here, as I have no mac : https://travis-ci.org/bartavelle/filecache/jobs/316932446

**Comment by jship** [comment]
I tested on OS X 10.13.2 and both `Should stop watching dropped files` and `Should update the list of watched files per directory` are failing.  From some debugging, looks like Remove events are not coming in from the event channel.  The Added events come in fine though.

There is a very old issue (https://github.com/haskell-fswatch/hfsnotify/issues/7) that @gregwebs hit, but looks like a refactoring worked for him.  I've only skimmed that issue, but will try the example code when I get a chance.

**Comment by bartavelle** [comment]
Thank you for looking into this! That would be awesome if you could test the refactoring.

**Pull request closed without merging**
