### PR TITLE
Cosmetic changes to make module deps more sane

### PR DESCRIPTION
**Pull request by PierreR**
A bunch of cosmetic changes that merely put some order in the module dependency graph.

I believe it makes the following dependency chain more explicit:
`Puppet.Language -> Puppet.Parser -> Puppet.Interpreter -> Puppet.Runner`

It allows to put datatype relevant to PuppetDB or Hiera in their own module and remove a couple of orphan instances.

My initial motivation behind this change (a part from code reading) was to fix the haddock issue in ghc-8.2 but I didn't manage to do that (I am still wondering what triggers this issue)

Let me know if there is something wrong in there.

### CODE REVIEW

**Comment by PierreR** [comment]
Some extra notes:

`ttext` has been renamed to `ppline`. There is no default Pretty instance for Text which forces the user to choose between `ppline` and `pplines`.
`string` from ansi-wl-pprint is not exposed in XPrelude and instead renamed with `ppstring`
`text` from ansi-wl-pprint is not exposed in XPrelude and instead renamed as `pptext`

It is always possible to be less idiomatic by using `XPrelude.Extra` && `XPrelude.PP`.
For instance we could decide to let `string` and `text` be exposed in `XPrelude.PP` and hide them in `XPrelude`. Normal usage is to go with `XPrelude` but if you wish for some short (and ill-named) functions from ansi-wl-pprint it is still possible to expose those through `XPrelude.PP`.

**Comment by bartavelle** [comment]
Looks good to me. I'll have to fix the hruby package though.

**Comment by bartavelle** [comment]
Build is fixed, despite what github says.

**Comment by PierreR** [comment]
I have managed to make `haddock` working again in ghc-8.2. Apparently a bug somewhere related to `makeClassy`.

It is rather disappointing to see that  `makeClassy` or `makeLenses` won't play nicely with `haddock` in general.

**Comment by bartavelle** [comment]
Do you have a reference for that lens/haddock bug? That is interesting.

**Comment by PierreR** [comment]
No real reference but I have submit an issue here: https://github.com/haskell/haddock/issues/679

Now that I know it is related to `makeClassy` it might be useful to compile a minimum example. And maybe the issue should be moved to the `lens` package ?

**Comment by PierreR** [comment]
More recent and precise information about the haddock issue: https://github.com/haskell/haddock/issues/710

**Pull request merged**
